# Generated by Django 2.2.5 on 2019-10-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20191019_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='id_gender',
        ),
        migrations.AddField(
            model_name='clients',
            name='Gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gender',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
